config/routes.rb
Rails.application.routes.draw do
  resources :news, only: [:index, :show] do
    resources :comments
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "news#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :news
end

app/models/news.rb
class News < ApplicationRecord
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  def is_admin?
    admin
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected 

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:admin, :name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:admin, :name])
    end

    def after_sign_in_path_for(resource)
        root_path
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_admin, only: :destroy

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to news_path(@comment.news), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to news_path(@comment.news), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to news_path(@comment.news), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:title, :description, :user_id, :news_id)
    end

    def authorize_admin
      unless current_user.is_admin?
        redirect_to news_comment_path(@comment.news, @comment), alert: 'Debes ser un administrador para poder borrar un comentario.'
      end
    end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @news = News.all
  end

  def show_comment
   @news = News.find(params[:id])
   @comments = @news.comments
  end

  def new_comment
    @comment = Comment.new
  end

  def show
    show_comment
    new_comment
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def admin_user
        current_user && current_user.is_admin?
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Titulo:</strong>
    <%= comment.title %>
  </p>

  <p>
    <strong>Comentario</strong>
    <%= comment.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>News:</strong>
    <%= comment.news_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, url:pag) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.hidden_field :user_id, value:current_user.id %>
  </div>

  <div>
    <%= form.label :news_id, style: "display: block" %>
    <%= form.hidden_field :news_id, value: @news.id %>
  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment, pag: news_comment_path(@comment.news, @comment) %>

<br>

<div>
  <%= link_to "Show this comment", news_comment_path(@comment.news, @comment) %> |
  <%= link_to "Back to comments", news_comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>


<div>
  <%if current_user.id == @comment.user.id %>
    <%= link_to "Edit this comment", edit_news_comment_path(@comment) %>
  <%end%>
  <%if admin_user%>
    <%= button_to "Destroy this comment", news_comment_path(@comment), method: :delete %>
  <%end%>
  <%= link_to "Back to comment", news_path(@comment.news) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Therialnews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="background-color: #1C2833;">
    <nav class="navbar bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand">The Rial News!!!!</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%=link_to "Home", news_index_path, class:"nav-link active"  %>   
              </li>            
              
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%=link_to "Sing Out", destroy_user_session_path, class:"nav-link active" %>   
                </li>
              <% end %>
              <% unless user_signed_in? %>
              <li class="nav-item">
                <%=link_to "Sign Up", new_user_registration_path, class:"nav-link active"  %>   
              </li>
              <li class="nav-item dropdown">
                <%=link_to " Log In", user_session_path, class:"nav-link active"  %>  
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </nav>
    <p class="notice"><%= notice %></p><p class="alert"><%= alert %></p>

    <div class= "container">
      <div class="p-3 mb-2 bg-black text-white">

        <%= yield %>

      </div>
    </div>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>

app/views/news/index.html.erb
<center><h1>The Rial News!</h1>
<p>Todas las semanas con nueva información para tu deleite (ñam ñam) </p>
</center>



<% @news.each do |n|%>
    
    <div class="card text-bg-dark mb-3" >
    <div class="card-header">
        <center><h5 class="card-title"><%= n.title %></h5>
    </div>
    <div class="card-body">
        <center><p class="card-text"><%= n.description %></p>
        <%=link_to "Comentarios", news_path(n), class:"btn btn-danger"  %>
    </div>
    <br>
<%end%>

app/views/news/show.html.erb
<center>
<h1>News!!!</h1>
<p>puedes comentar!!! Se parte de esta comunidad</p>
</center>
<br>
<br>
<div class="card text-bg-dark mb-3" >
    <div class="card-header">
        <center><h5 class="card-title"><%= @news.title %></h5>
    </div>
    <div class="card-body">
        <center><p class="card-text"><%= @news.description %></p>
    </div>
</div>
<br>
<center><h3>Comentarios</h3>


<% @comments.each do |n|%>
    <div class= "card text-bg-dark mb-3">
        <%= render "comments/comment", comment: n %>
        <% if user_signed_in?%>
            <%=link_to "Ver/Editar", news_comment_path(n.news, n), class:"btn btn-danger" %>
        <%end%>
    </div>
<%end%>

<% if user_signed_in? %>
    <%= render "comments/form", comment: @comment, pag: news_comments_path(@news) %>
<%end%>